spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your_url
    username: your_username
    password: your_password

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jwt:
    secret: your_jwt

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: your_port
  fileSrc: your_src
  url: http://your_url
  fileLocate: your_fileLocate
  uriFileLocate: file:///your_uriFileLocate





#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 2000
