spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guideme?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: localhost

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jwt:
    secret: asdfasdfasdfasdfasdfasdfqwqweqwerraasdfergghrqfqegrghs

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  fileSrc: /images/
  url: http://localhost:8080
#  fileLocate: C:/Users/MINU/Desktop/dummyFiles/
  fileLocate: C:/Users/CODELINE/Desktop/dummyFiles/
#  uriFileLocate: file:///C:/Users/MINU/Desktop/dummyFiles/
  uriFileLocate: file:///C:/Users/CODELINE/Desktop/dummyFiles/



#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 2000